name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install -r requirements-dev.txt
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
