name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Instalar dependências
        run: |
          pip install -q pipenv codecov
          pipenv sync --dev
      - name: testes
        run: |
          pytest --cov=libpythonpro_fls
      - name: Codecov
        env:
          CODECOV_TOKEN: '0418bf9b-2a55-4c89-a472-9c51c1183e6d'
        run: |
          codecov
